# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: database-persistent-volume-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

##Added on for local storage but not fully working